### ISSUE TITLE
how to use docker image?

### ISSUE THREAD

**Issue by QingyiZhang** [akaxincom/openzaly#14]
which port transfer to docker? 
write some how to will be better.

**Comment by haijohn** [comment]
below is the docker-compose.yml file i use
```
version: '2'
services:
  chat:
    image: java:8
    ports:
      - "2021:2021"
      - "8280:8280"
      - "8288:8288"
    volumes:
      - ".:/code"
    working_dir: /code
    command: java -jar -Dsite.admin.address=0.0.0.0 openzaly-server.jar
```
